#manual: data/evals/test/manual.csv
anthropic: data/evals/test/anthropic_hh_balanced.jsonl
toolace: data/evals/test/toolace_balanced.jsonl
mt: data/evals/test/mt_balanced.jsonl
mts: data/evals/test/mts_balanced.jsonl
mental_health: data/evals/test/mental_health_balanced.jsonl
redteaming: data/evals/test/aya_redteaming_balanced.jsonl
#mask: data/evals/test/mask_samples_balanced.jsonl
