#manual: data/evals/test/manual.csv
anthropic: data/evals/test/anthropic_hh_raw.jsonl
toolace: data/evals/test/toolace_raw.jsonl
mt: data/evals/test/mt_raw.jsonl
mts: data/evals/test/mts_raw.jsonl
mental_health: data/evals/test/mental_health_raw.jsonl
redteaming: data/evals/test/aya_redteaming_raw.jsonl
#mask: data/evals/test/mask_samples_raw.jsonl
